Data analyst and Data Scientist

    SQL
    - One shot Query
    - Programmers - MNC
    - Power BI - Charts

    Data Scientist
    - Excel
    - Line by line(step)
    - Python - numpy, pandas
    - Open-source
    - Scale 
    - Scikit - Data prediction
    - Matplot, seaborn - Charts


In [1]:
%pip install numpy




[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 15.8/15.8 MB 4.5 MB/s eta 0:00:00


## Numpy
- Work with Arrays
- Performant
- C language
- Statistical Orientated - mean, mode, std



In [2]:
import numpy as np

## Shortcuts
- `ctrl + alt + enter` --> Run the cell
- `shift + enter` --> Move to next cell

In [5]:
marks = np.array([90, 80, 20, 40])
marks_list = [90, 80, 20, 40]
marks_list * 2
marks * 2

array([180, 160,  40,  80])

## Python way to double the list

In [6]:
marks_list = [90, 80, 20, 40]
doubled_marks = [2 * mark for mark in marks_list]
print(doubled_marks)


[180, 160, 40, 80]


In [9]:
np.ones(200)
np.zeros(90)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [16]:
np.arange(10)
np.arange(1,10)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(10) > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [18]:
np.arange(10) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
first_ten_nums = np.arange(1,11)
all_gt_five = first_ten_nums > 5
first_ten_nums[first_ten_nums>5]
first_ten_nums[all_gt_five]

array([ 6,  7,  8,  9, 10])

## Task
Create a 1...200 numbers and provide a numpy array with all even numers

In [30]:
numbers_array = np.arange(0,201,2)
numbers_array


array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

## Task 2
Without the skip/step of arange

In [29]:
numbers_array = np.arange(201)
even_numbers_array = numbers_array[numbers_array % 2 == 0]
even_numbers_array

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
ages = np.random.randint(18, 60, 1_000_000)
ages_list = ages.tolist()
ages_list

In [ ]:
%%time
double_ages = [age * 2 for age in ages_list]
print(double_ages)

In [48]:
%%time
dbl_ages = ages * 2
dbl_ages

CPU times: total: 0 ns
Wall time: 2.01 ms


array([ 64,  96,  80, ...,  56, 112,  48])

## Statistical Orientated - mean, mode, median, std
- mean --> Average
- mode --> Most repeated number (most popular)
- median --> The middle value(In ordered list)
- standard deviation --> Average distance between mean and numbers

In [53]:
marks = np.random.randint(40, 100, 10)
print(marks)
marks.mean()
np.mean(marks)

[42 70 45 67 88 85 58 83 71 78]


68.7

In [54]:
np.median(marks)

70.5

In [55]:
np.sum(marks)

687

## Task 
Investment = 1_000
rate_of_interest --> 5%
1st year R50 --> 1_050
2nd year R52.50 --> 1_102.50

### Task 1
At the end of every year tell me the balance
[1050, 1102.50 ...]

### Task 2
At the end of 10 years what will be the balance?
Use slicing

### Task 3
How much % has it grown or increased compared to first year


In [70]:
import numpy as np

investment = 1000
rate_of_interest = 0.05

years = np.arange(1, 11)
balances = investment * (1 + rate_of_interest) ** years

balances


array([1050.        , 1102.5       , 1157.625     , 1215.50625   ,
       1276.2815625 , 1340.09564063, 1407.10042266, 1477.45544379,
       1551.32821598, 1628.89462678])

In [71]:
balance_at_10_years = balances[-1]  

print("Balance at the end of 10 years:", round(balance_at_10_years, 2))


Balance at the end of 10 years: 1628.89


In [72]:
balance_at_first_year = balances[0]
percentage_increase = ((balance_at_10_years - balance_at_first_year) / balance_at_first_year) * 100

print("Percentage increase compared to the balance at the end of the first year:", round(percentage_increase, 2), "%")

Percentage increase compared to the balance at the end of the first year: 55.13 %


## Useful methods
- String methods
- Unique
- Max, min

In [73]:
salaries = np.random.randint(1_000, 10_000, 10)
salaries


array([3042, 8820, 3843, 8588, 8669, 8285, 2934, 1923, 9441, 9851])

In [77]:
print(np.max(salaries), np.argmax(salaries))
print(np.min(salaries), np.argmin(salaries))

9851 9
1923 7


In [78]:
nums = np.random.randint(1, 4, 10)
nums

array([1, 1, 1, 1, 1, 3, 3, 1, 2, 1])

In [81]:
np.unique(nums)[::-1]
unique_nums = np.unique(nums)
np.flip(unique_nums)

array([3, 2, 1])

In [85]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
np.char.strip(items)


array(['Apple', 'banana', 'GRAPE', 'cucumber', 'Pineapple', 'tomato',
       'Orange', 'lemon', 'Kiwi', 'mango', 'blueberry', 'raspberry'],
      dtype='<U10')

## Task 1
Normlize the Array

Trim the leading and trailing spaces
Convert all to lowercase
Ensure there are no dup;icates

In [95]:
trimmed = np.char.strip(items)
low = np.char.lower(trimmed)
unique = np.unique(low)
print(unique)

np.unique(np.char.lower(np.char.strip(items)))

['apple' 'banana' 'blueberry' 'cucumber' 'grape' 'kiwi' 'lemon' 'mango'
 'orange' 'pineapple' 'raspberry' 'tomato']


array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U10')

## Task 2
Filtering Operations

a. Find and display all items that start with the letter "b"
b. Find and display all items that contain the letter "e" exactly once

In [93]:
start_with_b = np.char.startswith(unique, 'b')

contains_e_once = np.char.count(unique, 'e') == 1

print(unique[start_with_b])

print(unique[contains_e_once])

['banana' 'blueberry']
['apple' 'cucumber' 'grape' 'lemon' 'orange' 'raspberry']


## Task 3

hourly_visitors = [468 279 72 272 406 128 302 216 140 82]

- Find total visitors in the day
- Which is the peak hour?
- On average how many people visit the website per hour

In [102]:
hourly_visitors = np.array([468, 279, 73, 272, 406, 128, 302, 216, 140, 82])

total_visitors = np.sum(hourly_visitors)

peak_hour = np.argmax(hourly_visitors)

average_visitors_per_hour = np.mean(hourly_visitors)

print("Total visitors in the day:", total_visitors)
print("Peak hour:", peak_hour + 1)  
print("Average visitors per hour:", round(average_visitors_per_hour))

Total visitors in the day: 2366
Peak hour: 1
Average visitors per hour: 237


In [109]:
nums1 = np.arange(1,10)
print(nums1)
nums1.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [111]:
nums1.reshape(3,3).shape

(3, 3)

In [ ]:
nums_3x3 = nums1.reshape(3,3)
np.sum(nums_3x3)
np.mean(nums_3x3)
np.std(nums_3x3)


In [ ]:
print(nums_3x3)
np.sum(nums_3x3, axis=0)#column
np.sum(nums_3x3, axis=1)#row

np.sum(np.sum(nums_3x3, axis=1)) # entire sum

In [ ]:
nums_3x3 *2
nums_3x3 +2
nums_3x3 /2
nums_3x3 -2

In [105]:
stats = np.random.randint(40, 100, 9)
stats

array([88, 42, 58, 98, 81, 83, 98, 42, 71])

In [106]:
stats_3x3 = stats.reshape(3,3)
stats_3x3

array([[88, 42, 58],
       [98, 81, 83],
       [98, 42, 71]])

## Task 1
Find the average temperature of every part of the room
Expected output is a 3x3 matrix with average of sensors for each room



In [112]:
sensor1 = np.array(
    [
        [23,25,22],
        [20,21,20],
        [26,25,24]
    ]
)

sensor2 = np.array(
    [
        [24,23,24],
        [22,22,23],
        [25,26,26]
    ]
)

In [113]:
total_sensor_data = sensor1 + sensor2

average_temperature = total_sensor_data / 2 

print(average_temperature)

Average temperature of every part of the room:
[[23.5 24.  23. ]
 [21.  21.5 21.5]
 [25.5 25.5 25. ]]


In [115]:
avg_suite_temp1 = np.mean(sensor1,axis=1)
avg_suite_temp2 = np.mean(sensor2,axis=1)
 
print(avg_suite_temp1)
print(avg_suite_temp2)

[23.33333333 20.33333333 25.        ]
[23.66666667 22.33333333 25.66666667]


In [116]:
print((avg_suite_temp1+avg_suite_temp2)/2)

[23.5        21.33333333 25.33333333]
